[package]
name = "likec4-syntax"
description = "Lossless lexer, parser and syntax tree for the LikeC4 DSL"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
rowan.workspace = true
text-size.workspace = true
